# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from constants import globalConstants
from pathlib import Path
from datetime import date
from webdriver_manager.chrome import ChromeDriverManager

class TestTestshutbutton():
  def setup_method(self):
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
    self.folderPath =str (date.today())
    Path(self.folderPath).mkdir(exist_ok=True)
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_testshutbutton(self):
    self.driver.get(globalConstants.URL)
    self.driver.maximize_window()
    self.waitForElementVisible((By.ID, globalConstants.idButton))
    self.driver.find_element(By.ID, globalConstants.idButton).click()
    self.driver.find_element(By.ID, globalConstants.idButton).send_keys(" ")
    self.waitForElementVisible((By.ID, globalConstants.passwordButton))
    self.driver.find_element(By.ID, globalConstants.passwordButton).click()
    self.driver.find_element(By.ID, globalConstants.passwordButton).send_keys(" ")
    self.waitForElementVisible((By.ID, globalConstants.loginButton))
    self.driver.find_element(By.ID, globalConstants.loginButton).click()
    self.waitForElementVisible((By.XPATH, "//div[@id=\'login_button_container\']/div/form/div[3]/h3"))
    self.waitForElementVisible((By.CSS_SELECTOR, ".fa-times > path"))
    self.driver.find_element(By.CSS_SELECTOR, ".fa-times > path").click()


    self.driver.save_screenshot(f"{self.folderPath}/test-shut-button.png")
  def waitForElementVisible(self,locator,timeout=5):
    WebDriverWait(self.driver,timeout).until(expected_conditions.visibility_of_element_located(locator))

  
